version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    restart: always
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
      - 127.0.0.1:4160:4160
      - 127.0.0.1:4161:4161
    networks:
      - huancun

  nsqd:
    image: nsqio/nsq
    restart: always
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
      - 127.0.0.1:4150:4150
      - 127.0.0.1:4151:4151
    networks:
      - huancun
      
  nsqadmin:
    image: nsqio/nsq
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"
      - 127.0.0.1:4171:4171
    networks:
      - huancun

  redis-server:
    image: redis:latest
    restart: always
    container_name: redis
    privileged: true
    ports:
      - 127.0.0.1:6379:6379
    environment:
      TZ: Asia/Shanghai
    networks:
      - huancun

networks:
  huancun:
    driver: bridge